public class ToolingApiCtrl{

  /* {
  
  "Metadata" : {
    
    "label" : "Year",
    "type" : "Picklist",
    "valueSet" : {
      "valueSetDefinition" : {
        "sorted" : false,
        "value" : [ {
          "color" : null,
          "default" : false,
          "description" : null,
          "isActive" : null,
          "label" : "2019",
          "urls" : null,
          "valueName" : "2019"
        }, {
          "color" : null,
          "default" : false,
          "description" : null,
          "isActive" : null,
          "label" : "2020",
          "urls" : null,
          "valueName" : "2020"
        },{
          "color" : null,
          "default" : false,
          "description" : null,
          "isActive" : null,
          "label" : "2021",
          "urls" : null,
          "valueName" : "2021"
        } ]
      }
      
    }
  },
  "FullName" : "Account.Year__c" 
  */ /*
  HttpRequest req = new HttpRequest();
req.setHeader('Authorization', 'Bearer ' + UserInfo.getSessionID());
req.setHeader('Content-Type', 'application/json');
req.setEndpoint('https://lwcflows-dev-ed.my.salesforce.com/services/data/v50.0/tooling/sobjects/SobjectName?001&fields=00N2v00000YSG5v');
req.setMethod('GET');

Http h = new Http();
HttpResponse res = h.send(req);
system.debug(res.getBody()); */

}